Added support for setting TPM State in the BIOS
Cray-HPE/hms-scsd pull request #47
Opened 2022-06-15 16:13 UTC by shunr-hpe

### Summary and Scope

Added SCSD rest API to set the TPM State in the BIOS

DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N

### Issues and Related PRs

* Resolves CASMHMS-5535

### Testing

Tested on: groot (gigabyte) and baldar (hpe)

Were the install/upgrade based validation checks/tests run? Y
Were continuous integration tests run? Y
Was an Upgrade tested?                 Y
Was a Downgrade tested?                Y
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? NA

### Risks and Mitigations

The risk is low to existing scsd rest APIs. These changes add a new rest API

Requires:

* Additional testing on cray hardware
* These changes currently only support HPE and Gigabyte nodes. Once Castle (cray) hardware supports TPM state in the BIOS more changes will be needed.
* Support for Intel nodes is not fully implemented

2022-06-16 21:34 UTC, nieuwsma requested changes

2022-06-16 21:34 UTC, nieuwsma commented on api/openapi.yaml
> +  '/bmc/bios/{xname}/TpmState':
lower case the path

2022-06-16 21:34 UTC, nieuwsma commented on api/openapi.yaml
> +        '400':
use the Problem7807 body for these... 
If we cannot PAtch TpmState then return 400 and tell them the model isnt supported.

2022-06-21 19:18 UTC, shunr-hpe commented on api/openapi.yaml
> +  '/bmc/bios/{xname}/TpmState':
I changed TpmState to tpmstate

2022-06-29 14:20 UTC, mjendrysik-hpe approved these changes

2022-06-30 20:42 UTC, nieuwsma approved these changes

2022-06-30 21:21 UTC, merged